//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacman_Sevices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IRegisterService.Jugador", Namespace="http://schemas.datacontract.org/2004/07/Pacman_Sevices")]
    public partial class IRegisterServiceJugador : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CorreoField;
        
        private string CódigoField;
        
        private string NombreField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Código
        {
            get
            {
                return this.CódigoField;
            }
            set
            {
                this.CódigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBOperationResult.AddResult", Namespace="http://schemas.datacontract.org/2004/07/Pacman_Sevices")]
    public enum DBOperationResultAddResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NullObject = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknowFail = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExistingRecord = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ILoginService.Usuario", Namespace="http://schemas.datacontract.org/2004/07/Pacman_Sevices")]
    public partial class ILoginServiceUsuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IConfirmationServices.Jugador", Namespace="http://schemas.datacontract.org/2004/07/Pacman_Sevices")]
    public partial class IConfirmationServicesJugador : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CorreoField;
        
        private string CódigoField;
        
        private DataAccess.Usuario UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Código
        {
            get
            {
                return this.CódigoField;
            }
            set
            {
                this.CódigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataAccess.Usuario Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRegisterService")]
public interface IRegisterService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/AddUser", ReplyAction="http://tempuri.org/IRegisterService/AddUserResponse")]
    Pacman_Sevices.DBOperationResultAddResult AddUser(Pacman_Sevices.IRegisterServiceJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/AddUser", ReplyAction="http://tempuri.org/IRegisterService/AddUserResponse")]
    System.Threading.Tasks.Task<Pacman_Sevices.DBOperationResultAddResult> AddUserAsync(Pacman_Sevices.IRegisterServiceJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/SerachUserInDB", ReplyAction="http://tempuri.org/IRegisterService/SerachUserInDBResponse")]
    Pacman_Sevices.DBOperationResultAddResult SerachUserInDB(Pacman_Sevices.IRegisterServiceJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/SerachUserInDB", ReplyAction="http://tempuri.org/IRegisterService/SerachUserInDBResponse")]
    System.Threading.Tasks.Task<Pacman_Sevices.DBOperationResultAddResult> SerachUserInDBAsync(Pacman_Sevices.IRegisterServiceJugador jugador);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRegisterServiceChannel : IRegisterService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RegisterServiceClient : System.ServiceModel.ClientBase<IRegisterService>, IRegisterService
{
    
    public RegisterServiceClient()
    {
    }
    
    public RegisterServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RegisterServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegisterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegisterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Pacman_Sevices.DBOperationResultAddResult AddUser(Pacman_Sevices.IRegisterServiceJugador jugador)
    {
        return base.Channel.AddUser(jugador);
    }
    
    public System.Threading.Tasks.Task<Pacman_Sevices.DBOperationResultAddResult> AddUserAsync(Pacman_Sevices.IRegisterServiceJugador jugador)
    {
        return base.Channel.AddUserAsync(jugador);
    }
    
    public Pacman_Sevices.DBOperationResultAddResult SerachUserInDB(Pacman_Sevices.IRegisterServiceJugador jugador)
    {
        return base.Channel.SerachUserInDB(jugador);
    }
    
    public System.Threading.Tasks.Task<Pacman_Sevices.DBOperationResultAddResult> SerachUserInDBAsync(Pacman_Sevices.IRegisterServiceJugador jugador)
    {
        return base.Channel.SerachUserInDBAsync(jugador);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IChatService", CallbackContract=typeof(IChatServiceCallback))]
public interface IChatService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Connect", ReplyAction="http://tempuri.org/IChatService/ConnectResponse")]
    int Connect(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Connect", ReplyAction="http://tempuri.org/IChatService/ConnectResponse")]
    System.Threading.Tasks.Task<int> ConnectAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Disconnect", ReplyAction="http://tempuri.org/IChatService/DisconnectResponse")]
    void Disconnect(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Disconnect", ReplyAction="http://tempuri.org/IChatService/DisconnectResponse")]
    System.Threading.Tasks.Task DisconnectAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMsg")]
    void SendMsg(string message, int id);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMsg")]
    System.Threading.Tasks.Task SendMsgAsync(string message, int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/MsgCallback")]
    void MsgCallback(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatServiceChannel : IChatService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<IChatService>, IChatService
{
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    

    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public int Connect(string name)
    {
        return base.Channel.Connect(name);
    }
    
    public System.Threading.Tasks.Task<int> ConnectAsync(string name)
    {
        return base.Channel.ConnectAsync(name);
    }
    
    public void Disconnect(int id)
    {
        base.Channel.Disconnect(id);
    }
    
    public System.Threading.Tasks.Task DisconnectAsync(int id)
    {
        return base.Channel.DisconnectAsync(id);
    }
    
    public void SendMsg(string message, int id)
    {
        base.Channel.SendMsg(message, id);
    }
    
    public System.Threading.Tasks.Task SendMsgAsync(string message, int id)
    {
        return base.Channel.SendMsgAsync(message, id);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILoginService")]
public interface ILoginService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/ValidateUser", ReplyAction="http://tempuri.org/ILoginService/ValidateUserResponse")]
    int ValidateUser(Pacman_Sevices.ILoginServiceUsuario usuario);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/ValidateUser", ReplyAction="http://tempuri.org/ILoginService/ValidateUserResponse")]
    System.Threading.Tasks.Task<int> ValidateUserAsync(Pacman_Sevices.ILoginServiceUsuario usuario);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILoginServiceChannel : ILoginService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoginServiceClient : System.ServiceModel.ClientBase<ILoginService>, ILoginService
{
    
    public LoginServiceClient()
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int ValidateUser(Pacman_Sevices.ILoginServiceUsuario usuario)
    {
        return base.Channel.ValidateUser(usuario);
    }
    
    public System.Threading.Tasks.Task<int> ValidateUserAsync(Pacman_Sevices.ILoginServiceUsuario usuario)
    {
        return base.Channel.ValidateUserAsync(usuario);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IConfirmationServices")]
public interface IConfirmationServices
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationServices/SendEmail", ReplyAction="http://tempuri.org/IConfirmationServices/SendEmailResponse")]
    int SendEmail(Pacman_Sevices.IConfirmationServicesJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationServices/SendEmail", ReplyAction="http://tempuri.org/IConfirmationServices/SendEmailResponse")]
    System.Threading.Tasks.Task<int> SendEmailAsync(Pacman_Sevices.IConfirmationServicesJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationServices/GenerateNewCode", ReplyAction="http://tempuri.org/IConfirmationServices/GenerateNewCodeResponse")]
    int GenerateNewCode(Pacman_Sevices.IConfirmationServicesJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationServices/GenerateNewCode", ReplyAction="http://tempuri.org/IConfirmationServices/GenerateNewCodeResponse")]
    System.Threading.Tasks.Task<int> GenerateNewCodeAsync(Pacman_Sevices.IConfirmationServicesJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationServices/ChangeConfirmationStatus", ReplyAction="http://tempuri.org/IConfirmationServices/ChangeConfirmationStatusResponse")]
    int ChangeConfirmationStatus(Pacman_Sevices.IConfirmationServicesJugador jugador);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationServices/ChangeConfirmationStatus", ReplyAction="http://tempuri.org/IConfirmationServices/ChangeConfirmationStatusResponse")]
    System.Threading.Tasks.Task<int> ChangeConfirmationStatusAsync(Pacman_Sevices.IConfirmationServicesJugador jugador);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IConfirmationServicesChannel : IConfirmationServices, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ConfirmationServicesClient : System.ServiceModel.ClientBase<IConfirmationServices>, IConfirmationServices
{
    
    public ConfirmationServicesClient()
    {
    }
    
    public ConfirmationServicesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ConfirmationServicesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConfirmationServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConfirmationServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int SendEmail(Pacman_Sevices.IConfirmationServicesJugador jugador)
    {
        return base.Channel.SendEmail(jugador);
    }
    
    public System.Threading.Tasks.Task<int> SendEmailAsync(Pacman_Sevices.IConfirmationServicesJugador jugador)
    {
        return base.Channel.SendEmailAsync(jugador);
    }
    
    public int GenerateNewCode(Pacman_Sevices.IConfirmationServicesJugador jugador)
    {
        return base.Channel.GenerateNewCode(jugador);
    }
    
    public System.Threading.Tasks.Task<int> GenerateNewCodeAsync(Pacman_Sevices.IConfirmationServicesJugador jugador)
    {
        return base.Channel.GenerateNewCodeAsync(jugador);
    }
    
    public int ChangeConfirmationStatus(Pacman_Sevices.IConfirmationServicesJugador jugador)
    {
        return base.Channel.ChangeConfirmationStatus(jugador);
    }
    
    public System.Threading.Tasks.Task<int> ChangeConfirmationStatusAsync(Pacman_Sevices.IConfirmationServicesJugador jugador)
    {
        return base.Channel.ChangeConfirmationStatusAsync(jugador);
    }
}
namespace DataAccess
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConfirmaciónField;
        
        private string CódigoField;
        
        private int IdField;
        
        private DataAccess.Jugador JugadorField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Confirmación
        {
            get
            {
                return this.ConfirmaciónField;
            }
            set
            {
                this.ConfirmaciónField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Código
        {
            get
            {
                return this.CódigoField;
            }
            set
            {
                this.CódigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataAccess.Jugador Jugador
        {
            get
            {
                return this.JugadorField;
            }
            set
            {
                this.JugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CorreoField;
        
        private string EloField;
        
        private int IdField;
        
        private string NombreField;
        
        private string PantallasGanadasField;
        
        private string PuntuaciónField;
        
        private string PuntuaciónAltaField;
        
        private DataAccess.Ranking RankingField;
        
        private DataAccess.Usuario UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Elo
        {
            get
            {
                return this.EloField;
            }
            set
            {
                this.EloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PantallasGanadas
        {
            get
            {
                return this.PantallasGanadasField;
            }
            set
            {
                this.PantallasGanadasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puntuación
        {
            get
            {
                return this.PuntuaciónField;
            }
            set
            {
                this.PuntuaciónField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuntuaciónAlta
        {
            get
            {
                return this.PuntuaciónAltaField;
            }
            set
            {
                this.PuntuaciónAltaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataAccess.Ranking Ranking
        {
            get
            {
                return this.RankingField;
            }
            set
            {
                this.RankingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataAccess.Usuario Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ranking", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    public partial class Ranking : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private DataAccess.Jugador[] JugadorField;
        
        private string PosicionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataAccess.Jugador[] Jugador
        {
            get
            {
                return this.JugadorField;
            }
            set
            {
                this.JugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posicion
        {
            get
            {
                return this.PosicionField;
            }
            set
            {
                this.PosicionField = value;
            }
        }
    }
}
